name: Build with snapcraft

on:
  push:
    tags:
      - "v*.*.*"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
    - name: Update snap/snapcraft.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'snap/snapcraft.yaml'
        propertyPath: 'version'
        value: ${{ RELEASE_VERSION }}
        commitChange: false
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: serial-kiosk_${{ RELEASE_VERSION }}_amd64.snap
      # if: startsWith(github.ref, 'refs/tags/')
