name: Build with snapcraft

on:
  push:
    tags:
      - "v*.*.*"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Version
      id: set_version
      run: |
        echo "RELEASE_VERSION=$GITHUB_REF:11" >> "$GITHUB_ENV"
    - name: Update snap/snapcraft.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'snap/snapcraft.yaml'
        propertyPath: 'version'
        value: ${{ env.RELEASE_VERSION }} 
        commitChange: false
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: serial-kiosk_${{ env.RELEASE_VERSION }}_amd64.snap
      # if: startsWith(github.ref, 'refs/tags/')
